### ISSUE TITLE
Submodule cloning fails when submodule is another VSO repo

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vso-agent#134]
![image](https://cloud.githubusercontent.com/assets/22350/10794893/6a4ab54e-7d97-11e5-9302-f450bbf18e28.png)

**Comment by candril** [comment]
+1

**Comment by bryanmacfarlane** [comment]
BTW, the workaround is to prep the build machine with the creds (go in keychain etc... and add or clone manually to prep it).

There's two parts to this problem - different repo but in the same VSO collection/project.  That's much easier to solve since we generate an OAuth token for that build for that account/collection/project.  

If it's external (another account, GH) we need a new experience where you define creds you want the build machine to add to it's respective OSes cred store before the build happens.  Sort of a cred management experience.

**Comment by bryanmacfarlane** [comment]
Unauthenticated (open source) sub modules are only supported at this point.  If you want authenticated then you need to prep the key chain with creds

**Comment by candril** [comment]
@bryanmacfarlane thanks for the info. 

I need to checkout a submodule from the same team project. There are multiple repositories in one project. 

I manually stored the creds in the keychain (by doing a git clone on the server with a personal access token). This was still not working for me, when running builds with as a launch agent.
However, it is working when running builds in the interactive mode (node agent/vsoagent). This is also adding another keychain item with OAuth as user.

After that, builds running as an agent started working too. But I believe, that's because the (temp?) access token is stored in the .git/config file in the URL of the origin?

I think I still miss a step in configuring the credentials...
