### ISSUE TITLE
Maven capability not picked up

### ISSUE THREAD

**Issue by mmajcica** [Microsoft/vso-agent#169]
Dear,

maybe it is the expected behavior, still I couldn't find any reference to it. I have maven installed as suggested by this link https://maven.apache.org/guides/getting-started/windows-prerequisites.html . After installing the agent on that server, I do not see in the list of capabilities an entry called maven pointing to mvn file. Maven build step is expecting this capability to be set. Is this behavior expected or is this a bug?

Thanks

**Comment by mmajcica** [comment]
Please excuse me, issue is actually presenting itself in the windows vnext agent. However, if anyone can help or point me to the right direction, any help will be appreciated.

**Comment by bryanmacfarlane** [comment]
Capabilities basically try to find the tool.  Typically that's by being in the path.

Is maven resolvable via PATH?  If you type maven from a cmd prompt?

Next detail is what account is that build agent running as (running as a service?)  The default is network service - if it's in the PATH of your logged in account, perhaps network service can resolve it via it's paths.  If you can resolve it, you can try changing the account it runs as (note, you have to re-run agent config to do this since it sets ACLs).

Finally you can add that capability in the web UI on the agent so it routes there but note that when the task runs, it still needs to locate/find maven.

**Comment by LockTar** [comment]
I just had the same problem. This is how I fixed the issue:

1. Remove the registered agent
2. Go to the environment variables on your server in 'System'
3. Add two variables "MAVEN_HOME" and "M2_HOME" with both as value the installation directory of maven. In my case is this: "C:\Program Files\Java\apache-maven-3.3.9"
4. Restart server
5. Register agent again and voila, the agent should have the capabilitie: "MAVEN_HOME", "M2_HOME" and "**maven**"
