### ISSUE TITLE
Agent did not renew lock on Java builds

### ISSUE THREAD

**Issue by aes-charts** [Microsoft/vso-agent#285]
Hi There
We are getting below error while running Java build with ant scripts.
(): The job has been abandoned because agent AE-DT01-CI05_Lnx03 did not renew the lock. Ensure agent is running, not sleeping, and has not lost communication with the service.

**Comment by tarunaroraonline** [comment]
@aes-charts I think i know what the problem is, look at the agent control panel in administration console https://<accountName>.visualstudio.com/_admin/_AgentPool?hubGroupId=ms.vss-web.account-admin-hub-group&poolId=1&_a=agents. Look at agent capabilities, this will show you the agent properties. Look at agent AE-DT01-CI05_Lnx04 and AE-DT01-CI05_Lnx03, they both are configured on machine AE-DT01-CI05 and share the same config file.

**Comment by bryanmacfarlane** [comment]
0.6.5 has the fix where it could hang.
