### ISSUE TITLE
Disabling auto-update

### ISSUE THREAD

**Issue by mrquantize** [Microsoft/vso-agent#302]
Hi,

On Friday 6th May last week, the build tasks on our Windows and Linux build agents were automatically updated to newer versions which use the `const` keyword. This is not supported by older versions of Node.js. (`SyntaxError: Use of const in strict mode.`)

In order to prevent this issue from happening again, I decided to disable automate updates to the build agents. I noticed that on the Windows build agent, there is a file called settings.json which contained the line `"AutoUpdate": "True"`. I set this value to `False` and restarted the service, all seems well. However, I cannot find an equivalent settings file in the Linux vso-agent.

Is it possible to disable automatic updates in the same way?

P.S. saw the note about the future cross-platform service, seems like a good move.

**Comment by bryanmacfarlane** [comment]
It's actually the opposite.  The update carried a new version of node with ES6 capabilities so if you saw that error it's because your agent did not update for some reason.  Linux doesn't auto update so that's why.  You should switch to new agent on linux that does.  This agent is being deprecated: https://github.com/Microsoft/vsts-agent

The real consideration is tasks.  The system has complete versioning and the ability to bind to any version but we haven't finished the work to expose it in the definition editor.  That would allow you to step back or lock to a task version (in this case, new tasks depended on ES6)
