### ISSUE TITLE
On OSX, running as a service should use KeyChain for credentials (and not pass on cmdline via plist)

### ISSUE THREAD

**Issue by jmezach** [Microsoft/vso-agent#40]
I've setup the xplat agent on a Mac Mini and ran it as a service. Now if I run ps aux I see the following:

```
Administrator   22836   0.0  0.6  3050388  23788   ??  Ss   10:30AM   0:00.19 /usr/local/bin/node /Users/Shared/BuildAgents/Agent1/agent/host.js -u ZEUSTFSService -p somerandompassword
```

Obviously somerandompassword isn't the actual password for that account, but the point is that what I'm actually seeing on the screen is the correct password in clear text. This looks to me as a severe security problem since as long as I can access the machine I can see the password the agent is using to connect to TFS.

**Comment by bryanmacfarlane** [comment]
I have a workitem to use KeyChain.  I'll use this issue to track that work.

The mitigation right now is to control who you give the rights to log onto your build machine (obviously tougher if you're sharing a mac).  One other note is if you're connecting to VSO, PAT tokens will be enabled very soon.  That at least makes it so you can't just glance and remember a password (it's a long generated string).

**Comment by jmezach** [comment]
I'm aware of the support for personal access tokens on VSO. Unfortunately we're using TFS on-premise at the moment. Any chance PAT tokens are coming to on-premise TFS as well? Would be nice since connecting the xplat agent to TFS on-premise currently also requires basic authentication on the TFS server.

**Comment by bryanmacfarlane** [comment]
They are looking into for the next release.

The other item on my backlog for on-prem is xplat to support ntlm - but that doesn't help here - still have to persist the password.  What it will help with is not having to enable basic auth which if you do, you really need to use SSL so basic auth creds aren't going over the network base64 encoded (speed bump)

**Comment by ptoonen** [comment]
@bryanmacfarlane do you have any updates on NTLM support? Basic Auth has some security implications and I don't really want to create a larger attack surface on our environment than absolutely necessary.

**Comment by gravufo** [comment]
Bump! Updates would be nice, please!
Do you still plan on having NTLM support in the agent? And when would that happen approximately?

We are currently deploying in a test environment, so it's fine for now, but we definitely will not activate Basic Auth on the production environment.

Thanks!

**Comment by bryanmacfarlane** [comment]
We are actually going the other way - making on prem more like hosted.  On prem will support PAT tokens and IIS will not be the auth front gate.  Our app will enforce NTLM but a PAT token gets it through).  That means basic auth will not be required.

The timeline is the next release of TFS.

At the same time, the agents are being consolidated to a single core CLR agent (we were waiting on core CLR to get far enough along).  Same timeline.

Also, curious, basic should be basic + HTTPS/SSL.  That secures channel.  What's the production concern if configured that way?

**Comment by gravufo** [comment]
Thanks for the fast reply. Support for PAT would be ideal as it would work for Build Agents AND Tasks. I really like it.

Though, when you say next release of TFS, you mean the next major release? Not a quarterly update?

As for the deployment concerns, we were thinking that if we enable Basic Auth, we would have to disable HTTP and force HTTPS (because we don't want someone inadvertently falling onto Basic+HTTP), but as described in the following link, we find that it would complicate things for managing updates deployment and testing. Also client computers would need to be updated as we are only on HTTP right now. It would also affect the Git repositories we have.
https://msdn.microsoft.com/en-us/library/aa833872(v=vs.120).aspx#DisAd

I don't know if I'm just not seeing right, but forcing HTTPS is quite impactful. If you have any comments/suggestions, don't hesitate!

Thanks

**Comment by wmeints** [comment]
> Also, curious, basic should be basic + HTTPS/SSL. That secures channel. What's the production concern if configured that way?

The problem is not so much the transport over which we're sending the credentials to the agent. I'm happy to hear that it is using SSL though. The problem is that we have a shared buildserver and people can see the credentials in their build in clear text. That doesn't seem right to me.

Can't wait to get my hands on the next release! Just to clarify: We're talking update 2 or 3 somehting like that right?

**Comment by bryanmacfarlane** [comment]
@ wmeints

Once we support PAT tokens on prem, access to TFS resources is done via a per build and time bombed generated token which is sent to the agent as part of the build message and is never persisted.  That's the way VSTS works which is why we want on prem to work this way.

However, you will connect to the queue via a revocable PAT token which must be persisted.  That's why this issue is still open, the queue listening token should still be stored securely.

The combined single agent is slated for the next major release mainly because it's the server feature work and IIS config to allow these scenarios which is a pretty big shift.  But next major release shouldn't be too far off (no dates announced yet)

**Comment by wmeints** [comment]
Cool, good to know that you guys are planning on fixing this the proper way. I hope it doesn't take too long before we get another release :-) I've got quite a few developers waiting for this as they want to use our shared build server to build various Xamarin apps.

**Comment by bryanmacfarlane** [comment]
>>  I've got quite a few developers waiting for this as they want to use our shared build server to build various Xamarin apps.

To be clear, this is possible today.  You can run multiple agents on the same OSX machine.  That is, if they trust each other (or a subset of build admins are trusted - not all developers).

There's multiple requests here:
- No need to enable basic + SSL.  Yes - PAT token
- Token is revocable and not quite as risky (requires an effort - not a glance)
- Store that token in key chain.  Yes - very reasonable
- Untrusted teams can share the same OS instance.

Be aware that we don't even guarantee that last one on windows (we reimage the hosted build machines between builds).  On OSX you need to elevate to run as service etc... and we may not be able to guarantee isolation.  Docker on Linux may be closest to achieve that.  So, be aware that's an ask above what's planned for next release.  

Using Parallels on OSX to have multiple images for untrusted teams using the same hardware would be on solution (more RAM).  Another would be using macincloud integration but that's essentially another mac - just one you don't have to manage physically.

**Comment by bryanmacfarlane** [comment]
>> Untrusted teams can share the same OS instance

One other point:
Pools and agents are shared across the account so that's also possible today.  Each team can have projects, each with defintions.  Each definition targets a queue which is a securable pointer to the physical pool of agents.

So, many teams even across many projects can share the same agent (mac mini).  We do that at Microsoft with our VSO builds - many teams share a pool so it's elastic.  

We have a set of trusted build admins which have physical access to the machines.

**Comment by Mittchel** [comment]
@bryanmacfarlane Would you suggest just one BuildAgent for multiple projects?

Basically what scenario I've got in mind is:

1. User per customer/project, so certificates & provisioning profiles are seperated;
2. Central BuildAgents map in Macintosh HD;
3. BuildAgent per project/app;

Is this the correct way to tackle this? 

We do have a problem when the mac is rebooted I think. If we have a build agent per account this means we have to login every account manually since you can only have 1 auto logon account on Mac.

**Comment by bryanmacfarlane** [comment]
The replacement for this agent does pass creds as args. We are releasing a new preview tomorrow or early next week. It already has more features than this one

https://github.com/Microsoft/vsts-agent
